{{- if and (eq .Values.ingress.pattern "istio") (eq .Values.istio.pattern "sharedgateway") -}}
{{- $fullName := include "{{ .TemplateBuilder.Name }}.fullname" . -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ivs-{{ $fullName }}
  namespace: {{ .Release.Namespace }}
  {{ if .Values.tetrate.enabled }}
  annotations:
    tsb.tetrate.io/organization: {{ .Values.tetrate.organization }}
    tsb.tetrate.io/tenant: {{ .Values.tetrate.tenant }}
    tsb.tetrate.io/workspace: {{ .Values.tetrate.workspace }}
    tsb.tetrate.io/trafficGroup: {{ .Values.tetrate.trafficGroup }}
  {{ end }}   
spec:
  gateways:
  - {{ .Values.istio.sharedgateway.name }}
  hosts:
  - {{ .Values.istio.virtualService.host }}
  http:
  - name: canary-testing
    match:
    - headers:
        canary-test:
          exact: "yes"
      uri:
        prefix: {{ .Values.istio.virtualService.prefix }}
    rewrite:
      uri: {{ .Values.istio.virtualService.rewrite }}
    route:
    - destination:
        host: svc-{{ $fullName }}
        port:
          number: {{ .Values.istio.virtualService.route.destination.port.number }} 
        subset: canary
  - name: canary-rollout   # Referenced in canary.trafficRouting.istio.virtualService.routes in the Rollout yaml
    match:
    - uri:
        prefix: {{ .Values.istio.virtualService.prefix }}
    rewrite:
      uri: {{ .Values.istio.virtualService.rewrite }}
    route:
    - destination:
        host: svc-{{ $fullName }}
        port:
          number: {{ .Values.istio.virtualService.route.destination.port.number }}
        subset: stable
      weight: 100
    - destination:
        host: svc-{{ $fullName }}
        port:
          number: {{ .Values.istio.virtualService.route.destination.port.number }}
        subset: canary
      weight: 0 
{{ end }}