{{- $fullName := include "{{ .TemplateBuilder.Name }}.fullname" . -}}
{{- $labels := include "{{ .TemplateBuilder.Name }}.labels" . }}
{{- $release := .Release.Namespace }}
{{- $argoEnabled := .Values.argo.enabled -}}
{{ if and ( $val.hpa.enabled) ( not $val.keda.enabled ) }}
{{ $hpa := $val.hpa }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
    namespace: {{ $release }}
spec:
  scaleTargetRef:
    {{ if $argoEnabled }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{ else }}
    apiVersion: apps/v1
    kind: Deployment
    {{ end }}
    name: {{ $fullName }}
  minReplicas: {{ $hpa.minReplicas }}
  maxReplicas: {{ $hpa.maxReplicas }}
  metrics:
    {{- if $hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ $hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{ end }}
