{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "sa-{{ include "{{ .TemplateBuilder.Name }}.serviceAccountName" . }}"
  labels:
    {{- include "{{ .TemplateBuilder.Name }}.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
