# Default values for {{ .TemplateBuilder.Name }}.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tetrate:
  enabled: true
  organization: {{ .TemplateBuilder.Company }}
  tenant: {{ .TemplateBuilder.Company }}
  workspace: {{ .TemplateBuilder.ProductFamily }}-workspace
  trafficGroup: {{ .TemplateBuilder.ProductFamily }}-traffic
  
enabled: true
gateway: gwy-{{ .Release.Namespace }}
virtualService:
  host: {{ .TemplateBuilder.ProductFamily }}.{{ .TemplateBuilder.DnsLabel }}
  prefix: /{{ .TemplateBuilder.Name }}
  rewrite: /
  route:
    destination:
      port:
        number: 443
